# Generated by Django 5.2.16 on 2026-08-08 06:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_regax', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Format: +998901234567', regex='^\\+998\\d{9}$')])),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Format: +998901234567', regex='^\\+998\\d{9}$')])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('balance', models.BigIntegerField(default=0)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
