# Generated by Django 5.2.16 on 2026-08-07 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='students',
            field=models.ManyToManyField(related_name='attendances', through='attendance.AttendanceRecord', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('attendance', 'student')},
        ),
    ]
